# Generated by Django 3.2.3 on 2021-05-16 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='task',
            field=models.ManyToManyField(to='schedule_app.Task'),
        ),
    ]
